source 'http://rubygems.org'

gem 'thin'
gem 'hash_validator'
gem 'wei-backend'

group :test do
  gem 'rspec'
  gem 'rspec-html-matchers'
  gem 'rack-test'
end

group :development do
  gem 'rerun'
  gem 'shotgun'
end
